### ISSUE TITLE
Refactor Client

### ISSUE THREAD

**Issue by misha1235000** [meateam/SpikeClient#21]
## Todo:
Refactor the whole client side.

### Description
***Here are some of the changes needed:***
- [ ] Migrate from `Angular 9`, to `Angular 10`.
- [ ] Add `.env` to the client side (With the serving server)
- [ ] Change **ALL** the `.html` components, so they won't have style attribute, and move all of the style attributes to the css files with classes in the HTML.
- [ ] Change the debounce to be implemented the "Angular Way" using `rxjs` debounce.
- [ ] Think where its possible to use a generic component.
- [ ] Add more detailed comments where they are needed.

### Optional
- [ ] Add testing to the client side.
