### ISSUE TITLE
Design Scope Management Screen

### ISSUE THREAD

**Issue by shakedmanes** [meateam/SpikeClient#3]
### Todo
- [x] Design scope management screen for managing scopes belongs to clients (as service providers).
    The screen should contains:
    - [x]  A simple way to create scope for specific client (with all the properties of scope).
    - [x]  An intuitive table or UI Object which will represent the scopes properties and their owners (show which scope belong to which client).
    - [x] Maybe show which clients have permission to use the scope (only relevant for private scopes).

**Comment by shakedmanes** [comment]
## Attachement:
### Create new scope modal
![AddScopeModal](https://user-images.githubusercontent.com/33866657/84144877-a54c1d80-aa61-11ea-9664-e0cfadad1030.png)


### My Scopes Screen
![MyScopesScreen](https://user-images.githubusercontent.com/33866657/84144938-bc8b0b00-aa61-11ea-9681-075737112a64.png)


### Manage Scope's Permitted Clients Modal
![ManageClientsOfScopeModal](https://user-images.githubusercontent.com/33866657/84145025-d9bfd980-aa61-11ea-886f-6524f4439b13.png)


### Adding new Client to Scope
![ClientAddingToScopeModal](https://user-images.githubusercontent.com/33866657/84145084-ee9c6d00-aa61-11ea-82ff-785691a675fc.png)
![ClientAddingToScopeModalOPENED](https://user-images.githubusercontent.com/33866657/84145089-f1975d80-aa61-11ea-8241-a526fb97e839.png)
