### ISSUE TITLE
Design Scope Request Screen

### ISSUE THREAD

**Issue by shakedmanes** [meateam/SpikeClient#4]
### Todo
- [ ] Design scope request screen for requesting permissions to scopes that belong to 3rd party clients.       The screen should contain:
  - [ ] A simple way to find a client whom the user want to requests scopes permission from.
  - [ ] A simple way to view all scopes belongs to client, with full information of the scopes properties.
  - [ ] A simple way to request permission for specific scope, with indications of request status (pending, resolved, etc.)
  - [ ] A notification panel or button on navbar to indicate approvement or change in request status or incoming requests.
